version: '3'

networks: 
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.3.0/24

volumes:
  pgdata:
    driver: local

services:

  # dotnet:
  #  build: api
  #  container_name: dotnet
  #  ports:
  #    - 80:80
  #  networks:
  #    - default

  postgres:    
    container_name: postgres
    build: .docker/postgres
    restart: 'no'
    ports:
      - '5433:5432'
    volumes:
      - pgdata:${PSQL_PGDATA}
    environment:
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      PGDATA: ${PSQL_PGDATA}
    networks:
      - default
